name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./src  # Change ./src to the actual directory if your Go files are not in the root

    - name: Build the project
      run: go build -o main .
      working-directory: ./src  # Set the correct working directory

    - name: Run tests
      run: go test ./...
      working-directory: ./src  # Set the correct working directory

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: ./src/main  # Adjust the path if necessary
