name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy

    - name: Build the project
      run: go build -o main .
      working-directory: ./cmd


    - name: Run tests
      run: go test ./...

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: main
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: 2.29.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: yearzeroone/goapplication:latest


    - name: Deploy to EC2 with Docker Compose
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          script: |
            cd /home/ec2-user/go-movies/
            docker-compose pull
            docker-compose up -d




